### PR TITLE
Code upgrade to ES2015, Babel, React 0.14, Webpack

### PR DESCRIPTION
**Pull request by codeheroics**
- Build tools replacement (Webpack, Babel)
- React upgrade to v0.14
- ES2015

Reading commit by commit is probably a better idea for review than trying to read the whole diff in a single go!

### CODE REVIEW

**Comment by twidi** [comment]
Still looking at it. Seems great as far as i see. Didn't test it yet, though.

With ES6 maybe I don't need lodash anymore?

**Comment by codeheroics** [comment]
lodash is still super useful, in a lot of cases (examples which pop in my mind right now : deeply comparing objects, debouncing, throttling...)
I definitely recommend keeping it, even if it is not used a lot right now, it can, and probably will be useful later.

**Comment by twidi** [comment]
ok, got it.
I mainly thought of things like `map` for example.

**Comment by codeheroics** [comment]
Yes, `Array#map` is supported in JS since ES5, `_.map` is useful to map over collections - eg. if we need to map over an object's attribute.
Even functions available in ES2015 can still be useful in lodash though, lazy evaluation when chaining functions with lodash can be more efficient than iterating over and over in "plain" JS.

**Comment by twidi** [comment]
I agree, thanks. I'll have time to take a real look at you work this week-end ;)

**Review by twidi — CHANGES_REQUESTED** [review]
Every commit has a final comment. "Review ok" means it's ok, but the last ones have some remarks.

**Comment by codeheroics** [comment]
As you can imagine I have kind of forgotten about the changes I made here, but I'll do my best to answer your questions :)

**Comment by twidi** [comment]
Hey thanks you for your answers @codeheroics , I didn't expect them, I mostly did the review and the comments for myself!

I'll do some updates on your commits, based on my comments and merge it soon.

Again, thanks for the work, it's great to have split it up in commits, exactly how I like this kind of work to be done.

**Comment by twidi** [comment]
Next I'll port it to react 15 and webpack 2, then react 16. You greatly paved the way for this to be done easily. Also, as said in the past, it's easier for me to understand the changes from old-style-js to new-style one on a codebase I know!

**Comment by codeheroics** [comment]
Happy that my work has been useful, hopefully this will be a good starting point for what you have planned next :)

**Comment by twidi** [comment]
Closed in favor of #6 where I updated some commits and added some others (not all strictly related, but, you know... ;) )

**Pull request closed without merging**
